export { default as Login } from './Authentification/Login/Login'
export { default as Home } from './Home/Home'
export { default as Settings } from './Home/Settings/Settings'
export { default as Orders } from './Home/Orders/Orders'
export { default as SelectStore } from './Authentification/SelectStrore/SelectStore'
export { default as Header } from './Home/Header/Header'
export { default as Footer } from './Home/Footer/Footer'
export { default as All } from './Home/Orders/Stages/All/All'
export { default as InProgress } from './Home/Orders/Stages/InProgress/InProgress'
export { default as Ready } from './Home/Orders/Stages/Ready/Ready'
export { default as OrderDetailed } from './Home/Orders/OrderDetailed/OrderDetailed'
export { default as AcceptModal } from './Home/Orders/OrderDetailed/AcceptModal/AcceptModal'
export { default as Category } from './Home/Settings/Availability/Category/Category'
export { default as CategoryModal } from './Home/Settings/Availability/Category/CategoryModal/CategoryModal'
export { default as Product } from './Home/Settings/Availability/Category/Product/Product'
export { default as ProductModal } from './Home/Settings/Availability/Category/Product/ProductModal/ProductModal'
export { default as PrintingSetting } from './Home/Settings/PrintingSettings/PrintingSetting'
export { default as PrintingSettingsModal } from './Home/Settings/PrintingSettings/PrintingSettingsModal/PrintingSeetingsModal'
export { default as SearchPrinter } from './Home/Settings/PrintingSettings/SearchPrinter/PrinterSearch'
export { default as LanModal } from './Home/Settings/PrintingSettings/SearchPrinter/LanModal/LanModal'
export { default as DetailedPrinterSelected } from './Home/Settings/PrintingSettings/DetailedPrinterSelected/DetailedPrinterSelected'
export { default as PrintModal } from './Home/Orders/OrderDetailed/PrintModal/PrintModal'
export { default as BluetoothModal } from './Home/Settings/PrintingSettings/SearchPrinter/BluetoothModal/BluetoothModal'
export { default as RejectModal } from './Home/Orders/Stages/All/RejectModal/RejectModal'

export { default as RejectOrdersDetailedModal } from './Home/Orders/OrderDetailed/RejectModal/RejectModal'
export { default as ForgotPassword } from './Authentification/ForgotPassword/ForgotPassword'
export { default as ResetPassword } from './Authentification/ResetPassword/ResetPassword'


export { default as Languages } from './Home/Settings/Languages/Languages'

